version: '3.8'

services:
  hanoisun-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: hanoisun-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    networks:
      - hanoisun-dev-network
    command: npm run dev

networks:
  hanoisun-dev-network:
    driver: bridge
